version: 2

models:
  - name: crypto_raw
    description: Raw cryptocurrency data ingested from Kafka
    columns:
      - name: id
        description: Unique identifier for the record
        data_tests:
          - not_null
          - unique
      - name: symbol
        description: Cryptocurrency symbol (e.g., BTC, ETH)
        data_tests:
          - not_null
          - not_empty_string  # Generic test for empty strings
      - name: name
        description: Full name of the cryptocurrency
        data_tests:
          - not_null
          - not_empty_string  # Generic test for empty strings
      - name: price
        description: Current price of the cryptocurrency
        data_tests:
          - not_null
          - price_in_range:  # Generic test with parameters
              min_value: 0
              max_value: 1000000
      - name: date_and_time
        description: Timestamp when the data was last updated
        data_tests:
          - not_null

    data_tests:
      - no_duplicate_ids:  # Specific test for duplicates in time window
          column_name: id