version: 2

models:
  - name: crypto_curated
    description: Curated cryptocurrency data for analytics and business use
    columns:
      - name: id
        description: Unique identifier for the record
        data_tests:
          - not_null
          - unique
      - name: symbol
        description: Cryptocurrency symbol
        data_tests:
          - not_null
          - not_empty_string  # Generic test for empty strings
      - name: name
        description: Cryptocurrency name
        data_tests:
          - not_null
          - not_empty_string  # Generic test for empty strings
      - name: price
        description: Cryptocurrency price
        data_tests:
          - not_null
          - price_in_range:  # Generic test with parameters
              min_value: 0
              max_value: 1000000
      - name: date_and_time
        description: Timestamp of the data
        data_tests:
          - not_null
