kafka_athena_dbt:
  outputs:
    dev:
      aws_access_key_id: 
      aws_secret_access_key: 
      database: awsdatacatalog
      region_name: us-east-1
      s3_data_dir: s3://gr-andfh/data/
      s3_staging_dir: s3://gr-andfh/
      schema: crypto_analytics
      threads: 1
      type: athena
  target: dev